### ISSUE TITLE
Kleiner Fehler in Anleitung: echo fehlt

### ISSUE THREAD

**Issue by pschuenemann** [JsBergbau/BaikalAnleitung#10]
Hallo @JsBergbau,

in meinen verschiedenen Tests ist mir aufgefallen, dass im nullmailer-Abschnitt deiner Anleitung im Satz 

> Um das auch via Kommandozeile zu testen `"Subject: sendmail test" | sendmail -v eure@zieladresse.domain`

irgendwie was fehlt - insbesondere ein `echo` im Befehl.

Vielleicht kann man alternativ schreiben: 

> Um das auch via Kommandozeile zu testen, gebt ihr einfach `echo "Subject: sendmail test" | sendmail -v eure@zieladresse.domain` ein.

 (Das `-v` ist glaub ich auch nicht nötig, aber da bin ich nicht wirklich dahinter gestiegen was das macht.)

Vielleicht kannst du das noch ändern, damit Linuxanfänger, wie ich, da nicht drüber stolpern.

Viele Grüße

**Comment by JsBergbau** [comment]
Vielen dank für den Hinweis. Du hast natürlich recht, ein echo ist notwendig. Ohne das echo gibt es eine komplett leere E-Mail ohne einen Betreff. Ist jetzt ausgebessert. Das `-v` ist tatsächlich nicht notwendig. Es soll nur mehr Infos anzeigen, wobei in meinem Test gerade sendmail weder mit noch ohne `-v` eine Meldung ausgegeben hat.

**Comment by pschuenemann** [comment]
Super, danke!

Bei mir ging es ohne `echo` tatsächlich gar nicht. Hab da immer irgendwie einen Fehler bekommen, dass der Befehl Subject unbekannt ist oder so ähnlich. Wie auch immer, mit `echo` funktioniert es dann auf jeden Fall für alle, wie gewünscht.

Vielen, vielen Dank übrigens für die tolle detaillierte und verständliche Anleitung!!!

**Comment by JsBergbau** [comment]
Es kommt eine Fehlermeldung, weil Subject als Befehl interpretiert wird. Durch die Pipe wird dann der 2. Teil ausgeführt. Weil da nichts reingeht wird eine vollständig leere Mail ohne Betreff und Inhalt losgesendet. Eventuell hat hier dein Mailserver bzw. Provider diese Mail ausgefiltert.

> Vielen, vielen Dank übrigens für die tolle detaillierte und verständliche Anleitung!!!

Bitteschön. Das freut mich sehr, dass die Anleitung auch für weniger IT-affine Interessierte verständlich und nachvollziehbar ist.
