### ISSUE TITLE
Baikal und macOS-Clients

### ISSUE THREAD

**Issue by truscobox** [JsBergbau/BaikalAnleitung#11]
Um von einem aktuellen Mac auf Baikal zugreifen zu können, muss man die folgende Änderung in htaccess vornehmen, dann funktioniert es tadellos (Mac Addressbuch, Erinnerungen (Aufgaben) und Kalender, unter macOS 11.3.2):

![htaccess](https://user-images.githubusercontent.com/78899500/117533560-c90b4100-afed-11eb-9b19-1b234c47d374.jpg)

**Comment by JsBergbau** [comment]
Hi truscobox,
hast du Apache oder nginx als Webserver? Ich bin nicht der Webserver-Spezialist, aber die Syntax aus deinem Screenshot sieht mir ganz nach Apache aus. Es steht sogar etwas von Apache drinnen...

In der Beispielkonfiguration für nginx sind ja bereits die Zeilen
```
 rewrite ^/.well-known/caldav /dav.php redirect;
 rewrite ^/.well-known/carddav /dav.php redirect;
```

enthalten. Diese hatte ich irgendeinem Tutorial entnommen und wenn ich mich richtig erinnere ging es dabei genau um Apple-Geräte.

**Comment by truscobox** [comment]
Hallo JsBergbau,

der Baikal-Server läuft auf nginx. Die versteckte _.htaccess_-Datei ist im Baikal-Paket mit dabei. In irgendeinem Forum habe ich den Tipp gefunden, die beiden Zeilen um das `/html` zu ergänzen, also
```
rewrite ^/.well-known/caldav /html/dav.php redirect;
rewrite ^/.well-known/carddav html/dav.php redirect;
```
Wo ich den Hinweis damals gefunden habe, erinnere ich nicht mehr. Das Problem ist anscheinend, dass die neueren mac-Clients den Pfad mit `/html` benötigen.

Die anderen Clients wie DAVx5 funktionieren nach der Änderung wie gewohnt.

**Comment by JsBergbau** [comment]
Kannst du mal bitte deine komplette baikal-nginx.site Konfiguration hier schreiben?

**Comment by truscobox** [comment]
```
server {

    listen 9998 default_server;

    #listen [::]:80 default_server;
    # SSL configuration
    #
    # listen 443 ssl default_server;
    # listen [::]:443 ssl default_server;
    #
    # Note: You should disable gzip for SSL traffic.
    # See: https://bugs.debian.org/773332
    #
    # Read up on ssl_ciphers to ensure a secure configuration.
    # See: https://bugs.debian.org/765782
    #
    # Self signed certs generated by the ssl-cert package
    # Don't use them in a production server!
    #
    # include snippets/snakeoil.conf;
    #root /var/www/html;

    root /home/pi/Services/Baikal/html;

    # Add index.php to the list if you are using PHP

    index index.php index.html index.htm index.nginx-debian.html;
    server_name _;

    # location / {
    #     First attempt to serve request as file, then
    #     as directory, then fall back to displaying a 404. try_files $uri $uri/ =404;
    # }

    rewrite ^/.well-known/caldav /dav.php redirect;
    rewrite ^/.well-known/carddav /dav.php redirect;
    charset utf-8;

    location ~ /(\.ht|Core|Specific|config) {
        deny all;
        return 404;
    } #In der aktuellen Variante nicht benötigt, da "html" das Root Verzeichnis ist, schadet aber auch nicht.
	 #Sollte man Baikal jedoch direkt im Webserver als Unterverzeichnis installieren, absolut notwendig. Bitte daran denken!

    location ~ ^(.+.php)(.*)$ {
        try_files $fastcgi_script_name =404;
        include /etc/nginx/fastcgi_params;
        fastcgi_split_path_info ^(.+.php)(.*)$;
        fastcgi_pass unix:/run/php/php7.3-fpm.sock; #Hier auf eure installierte PHP-Version achten. 
	#fastcgi_pass unix:/run/php/php7.4-fpm.sock; #Ubuntu hat z.B. schon php 7.4
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #

    location ~ /.ht {
        deny all;
    }

}

```

**Comment by JsBergbau** [comment]
Es ist komisch, denn nginx unterstützt keine .htaccess Dateien. Die Datei kommt zwar mit, das ist richtig, wird aber von nginx nicht ausgewertet. Daher wundert es mich, dass eine Änderung dort Auswirkungen bei dir haben. 

https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/

> You can’t do this. You shouldn’t. If you need .htaccess, you’re probably doing it wrong.

Die dortige Logik wurde direkt in die nginx-Konfiguration übernommen

```
 rewrite ^/.well-known/caldav /dav.php redirect;
    rewrite ^/.well-known/carddav /dav.php redirect;
```
Und da der Dokumentroot bei dir korrekterweise `    root /home/pi/Services/Baikal/html; ` lautet, findet er dann unter <IP:9998>/dav.php auch die Datei. Wenn du auf /html/dav.php umleitest, kann er die Datei gar nicht finden, weil er dann auf <IP:9998>/html/dav.php umgeleitet wird. Probier es aus, gibt letzteren Pfad im Browser ein und du wirst einen 404 Fehler bekommen. Wenn nicht, dann läuft etwas schief.

**Comment by truscobox** [comment]
Du hast vollkommen recht, die Änderung in  ._htaccess_ hat überhaupt keine Auswirkung. Ich kann leider auch nicht mehr nachvollziehen, was ich damals noch geändert habe und müsste es noch einmal auf einem neuen System ausprobieren.

Der einzige Unterschied, den ich bemerkt habe, ist, dass auf dem alten Gerät (OS X 10.6.8) _card.php_ und _cal.php_ in den Einstellungen angegeben sind und auf dem neueren beides mal _dav.php_.
