### ISSUE TITLE
Radicale: Nachteile

### ISSUE THREAD

**Issue by Psychi1** [JsBergbau/BaikalAnleitung#12]
Hi,

du schreibst unter Alternativen, dass bei Radicale "Freigabe von Kalendern zwischen Benutzern [] nicht möglich" ist. 

Das ist in dieser absoluten Form nicht richtig. Mit Hilfe von symbolischen Links und geschickter Anwendung von Rechten, lassen sich Kalender sehr wohl freigeben. Dies kann jedoch nur vom Admin eingestellt werden. 

Ein großer, unerwähnter Nachteil ist die fehlende Einladungs-Funktion bei Radicale.

Ciao

**Comment by JsBergbau** [comment]
Hi Psychi1,

danke für den Hinweis.
Was meinst du mit Einladungsfunktion? Dass automatisch Mails verschickt werden?

**Comment by Psychi1** [comment]
Hi,

Genau. Es gibt bei Radicale keine Möglichkeit Einladungen per Mail zu versenden.

**Comment by JsBergbau** [comment]
Dankeschön. Die Anleitung wurde angepasst.
