### ISSUE TITLE
Not possible to enable Baikel Calendar Thunderbird

### ISSUE THREAD

**Issue by warfriet** [JsBergbau/BaikalAnleitung#14]
I have installed Baikel on my QNAP and that works with my mobile phone.

Now I have installed it on Thunderbird to with 2 addons:
- Provider for CalDAV & CardDAV
- TbSync
Both are working properly.

When I click to enable the Calendar it's automatic turned off again.

How to solve this issue?

![210806-02](https://user-images.githubusercontent.com/46873506/128521443-5f3270a2-6d35-4aae-a6cb-052d05fe415d.JPG)
![210806-01](https://user-images.githubusercontent.com/46873506/128521444-4699a2c7-85f8-45c8-bcd3-01a80f1932b8.JPG)

**Comment by JsBergbau** [comment]
Hallo,

with current Thunderbird 78 you don't need any Addon. I've updated the instructions for Thunderbird. Please uninstall the addons and try again. Since it works with your mobile phone this can only be a thunderbird problem. If you have still trouble, please try with a fresh profile or a Thunderbird Portable https://portableapps.com/de/apps/internet/thunderbird_portable

**Comment by warfriet** [comment]
I removed all addons and tried it. Have the same issue.
I installed Thunderbird Portable. Also the same issue.

Lets hope it will work the next Thunderbird version.
Is there an alternative Calendar that works on a Windows PC?

**Comment by JsBergbau** [comment]
Did you copy the correct URL as described here https://github.com/JsBergbau/BaikalAnleitung#benutzerlogin ?
I'm using Thunderbird 78.12.0 32 Bit and it works flawlessly.
Try saving the password in Thunderbird. I had some problems when not saving the password.

**Comment by warfriet** [comment]
When I am create a new calendar, Thunderbird don't ask for a password!
Looks like there goes something wrong.

**Comment by Bl8Runnr** [comment]
> When I am create a new calendar, Thunderbird don't ask for a password! Looks like there goes something wrong.

This is the problem- if TB doesn't ask for a password, it will link the calendar write protected.
In my case: `http://192.168.1.5:9999/dav.php/[user]/[calendar_name] `will not ask for a password and just open the calendar for display. Removing `[user]/[calendar_name]` will ask for password and give you full access to the calendar.

Note: This seems to only be an issue in TB, but not in DAVX5 for example.

Solution is, to use the following format: https://yourdomain.tld:yourport/dav.php
Now TB will search for any calendar here and ask for a password.

Hope this helps!
Best regards
Jens

**Comment by warfriet** [comment]
It works now. I have changed the "WebDAV authentication type" to Digest and then it works with all my devices.

Hope this helps for others to!
Best regards
Emil
