### ISSUE TITLE
Question webserver

### ISSUE THREAD

**Issue by ChillyFV** [JsBergbau/BaikalAnleitung#17]
Hello,
thank you for the great help with creating an own server for my calendar. I got to the point "Webserver-Konfiguration" but at the beginning of this section I'm stuck. How should I create that file? Thank you for your help!
Best,
ChillyFV

PS: I'm german...

**Comment by JsBergbau** [comment]
Hallo ChillyFV,
ich antworte mal auf Deutsch, da die Anleitung auf Deutsch ist und du nochmal darauf hinweist, dass du Deutsch bist.

Du kannst die Datei im Verzeichnis Baikal z.B. via `nano baikal-nginx.site` erstellen. Die Anleitung ist auch schon ergänzt für künftige Leser.

**Comment by ChillyFV** [comment]
Hi JsBergbau,

hab vielen Dank für deine Antwort und deine Hilfe, das hat super funktioniert! Der Pi mit Baikal läuft bereits und sieht gut aus. Eine Verständnisfrage hätte ich noch (da ich zum ersten Mal mit einem CalDAV-Server arbeite): Wenn ich nun
1) einen Kalender auf Baikal erstelle
2) über mein Handy in diesen erstellten Kalender ein Backup meines aktuelle Offline-Kalenders einspiele
3) und der Pi irgendwann mal abstürzt und keine Verbindung mehr zum Handy besteht: Sind alle Einträge weg? Oder werden die Einträge trotzdem lokal auf meinem Handy gespeichert und auf dem Baikal-Server eine Kopie dieser Einträge erstellt? Oder vielleicht anders gefragt: Wo liegen die Kalender-Einträge (die ich möglichst per Backup sichern sollte): Weiter lokal auf meinem Handy oder nur online auf dem Server?

Hab vielen Dank für deine Antwort und liebe Grüße!

**Comment by JsBergbau** [comment]
Hi ChillyFV,

mittels DAVx5 werden die Einträge zwischen deinem Handy und dem Rasbperry PI in regelmäßigen Abständen synchronisiert, d.h. die Daten sind auf beiden gespeichert. 
Die Einträge auf dem Server / Raspberry PI kannst du via http://<IP>:9999/dav.php/calendars/<benutzername>/default/ im Browser einsehen.
Schau dir nochmal den Abschnitt https://github.com/JsBergbau/BaikalAnleitung#benutzerlogin an und klicke dich ein bisschen in der Weboberfläche umher um selbst ein Verständnis für das System zu bekommen.

**Comment by ChillyFV** [comment]
Super, das hat mir sehr geholfen, danke :)
