### ISSUE TITLE
Connecting without WiFi

### ISSUE THREAD

**Issue by ChillyFV** [JsBergbau/BaikalAnleitung#18]
Hi JsBergbau,
I installed baikal successfully on my Pi some months ago and I am very happy with it! I have one question regarding the connection to the device: I will move in some days and therefore my internet contract ended. The router is already send back and no longer available. Unfortunately I just realized that I have no longer the possibility to connect the Pi to my computer to change the WiFi settings to the new WiFi in the new flat. Can you tell me how I can access the Pi and baikal to change the setting to the new WiFi so everything works again fine?
Thank you very much in advance!
Best,
Julian

**Comment by JsBergbau** [comment]
Hi ChillyFV,

basically this is not a Baikal issue, but simply raspberry PI. 
You can connect a monitor and keyboard to edit /etc/wpa_supplicant.conf

Or you put a pre-configured wpa_supplicant.conf to /boot partition and it should also work.

If you need further help please ask at a dedicated forum like https://forums.raspberrypi.com/
