### ISSUE TITLE
alternate User-Interface

### ISSUE THREAD

**Issue by cptsanifair** [JsBergbau/BaikalAnleitung#20]
Hi,

thx a lot for your description. As additional tipp i want to show you InfCloud [https://inf-it.com/open-source/clients/infcloud/] 

You can set it up in a subdirectory, (like https://your-baikal/infcloud) and manage contacts, tasks and your calandar with  

regards

**Comment by JsBergbau** [comment]
Vielen Dank. Ich habe diese Möglichkeit in die Anleitung aufgenommen https://github.com/JsBergbau/BaikalAnleitung/blob/master/README.md#browser
Um es selbst einzurichten und eine detaillierte Anleitung zu erstellen fehlt mir im Moment die Zeit/Motivation.
