### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by blockcrafter21** [JsBergbau/BaikalAnleitung#21]
Ich bekomme beim Zugriff einen 403 Fehler, an den Berechtigungen für die Ordner sollte es ja eigentlich nicht liegen.

**Comment by JsBergbau** [comment]
Wo genau erhälst du denn den Fehler? 
Welche Hinweise geben /var/log/nginx/access.log und /var/log/nginx/error.log?

**Comment by blockcrafter21** [comment]
Aus irgendeinem Grund geht es wieder, lol
