### ISSUE TITLE
[Feature Request] Guide mehr Distributions-Unabhängig machen und an Standard orientieren

### ISSUE THREAD

**Issue by toby63** [JsBergbau/BaikalAnleitung#24]
So sehr ich den Guide an sich begrüße und ich ausdrücklich einige Details loben möchte, die in vielen anderen Anleitungen generell so nicht zu finden sind, so gibt es doch einige Stellen an denen man als unerfahrener Nutzer eventuell seine Probleme haben kann.

Wünschenswert wären insbesondere folgende Sachen:
1. SSL Setup, aus sicherheitsgründen usw. wäre das eigentlich Standard in den meisten ähnlichen Anleitungen.
     Die Modifikationen in der config sind ja auch dankbarer Weise kurz (wenn man sich denn auskennt), für alles weitere z.b. Zertifikate erstellen usw. könnte man ja auf Drittseiten verweisen.
2. Standardports sind eigentlich die üblichen Webserver Ports und eine Anleitung sollte ja normalerweise auch den Standardfall abdecken.
3. Standardordner ist auch eigentlich sowas wie /var/www/* und nicht das /home Verzeichnis.
4. Dependencies könnte man auch Distributions-unabhängig formulieren, insbesondere könnte man auch zu aktivierende Extensions in PHP erwähnen.
5. Der php-fpm socket ist nicht bei allen Distros so aufgebaut, im Zweifelsfall kommt es auf die installierte Version an (leider erwähnt Upstream in ihrer kurzen Anleitung auch nicht, dass php8 mittlerweile unterstützt wird) und nicht auf die Zahl.
6. Der user "www-data:www-data" ist auch nicht überall gleich, entscheidend ist der user der in der nginx config benutzt wird.
7. "/etc/nginx/sites-enabled/" ist auch nicht überall standard, sondern muss manchmal seperat aktiviert werden.
8. "http://<IP>:9999" ist auch nicht unbedingt der Link, z.b. könnte es eben auch eine Domain und https sein, und bei Standardports auch ohne ports aufrufbar.
9. Der Zugriff in Clients könnte ebenfalls plattform-unabhängiger formuliert sein, indem man z.b. erstmal auf eine "Standard-URL" hinweißt, die hier sogar an anderer Stelle, nämlich als Web-Zugriff erwähnt wird: http://<IP>:9999/dav.php
     Die meisten Clients die ich ausprobiert habe, brauchten diese URL mit Zusatz "/dav.php".

Ich hoffe man nimmt mir diesen Vorschlag nicht zu übel, aber da dies die einzige brauchbare Anleitung ist (die ich gefunden habe), dachte ich ich bitte einfach mal um einige IMHO sinnvolle Änderungen.

**Comment by JsBergbau** [comment]
Hi toby63,

danke für deine Anregungen.

> SSL Setup, aus sicherheitsgründen usw. wäre das eigentlich Standard in den meisten ähnlichen Anleitungen.

Prinzipiell hast du da recht. Es kommt eben auf den Anwendungsfall an. Ich gehe gerne auf Nummer sicher und gebe den Server nicht im Internet frei, sondern lediglich zu Hause bzw. via VPN. Dadurch muss man sich auch nicht ständig um Updates kümmern, was der Standardnutzer gerne mal vergisst. Für SSL braucht es dann auch noch eine Domain/DyDNS, damit Let's Encrypt funktioniert. Das ist für den Standardnutzer nochmal eine Hürde höher, die ihn vielleicht davon abhält und stattdessen seine Kontakte und Kalender leider weiterhin Google überlässt.

> Standardports sind eigentlich die üblichen Webserver Ports und eine Anleitung sollte ja normalerweise auch den Standardfall abdecken.

Gerade wenn du es im Internet freigibst, ziehst du dir damit noch mehr Aufmerksamkeit auf dich. Ich habe einen SSH-Server auf einem nicht Standardport. Bis heute gibt es darauf keine Loginversuche.

> Standardordner ist auch eigentlich sowas wie /var/www/* und nicht das /home Verzeichnis.
Ich habe gerne das Homeverzeichnis, da ich so weiß, was alles auf diesem System läuft und man nichts vergisst. Finde ich persönlich sicherer.

Zu 3 bis 7: Da ich es für den Raspberry PI geschrieben habe und das Debian ist, ist das da alles gleich.

Zu 8 bis 9: Es liegt der Fokus auf dem lokalen Netzwerk, siehe auch oben zu SSL.

> Ich hoffe man nimmt mir diesen Vorschlag nicht zu übel, aber da dies die einzige brauchbare Anleitung ist (die ich gefunden habe), dachte ich ich bitte einfach mal um einige IMHO sinnvolle Änderungen.

Danke für die Lorbeeren. Ich bin noch unschlüssig, ob/was ich daran ändern soll. Guten Gewissens kann ich gerade einem unerfahrenem User, für den diese Schritt für Schrittanleitung ist, nicht empfehlen den Server öffentich im Internet von überall aus zugreifbar zu machen.

**Comment by toby63** [comment]
@JsBergbau Ich respektiere natürlich ihre Entscheidung, den Fokus ihrer Anleitung so zu wählen, aber da diese Anleitung sogar upstream empfohlen wird und somit viele Nutzer (auch etwas erfahrenere, keine Debian-Nutzer, https Interessierte usw.) anzieht, wäre es schön gewesen auf meine Vorschläge einzugehen, aber wenn Sie dies ablehnen, muss ich das natürlich akzeptieren.

Eventuell könnten Sie zumindest darauf hinweisen, dass diese Anleitung Änderungen enthält die vom Standard abweichen und eigentlich nur für die Nutzung im lokalen Netzwerk gedacht ist.

Ich werde eventuell versuchen upstream eine Anleitung oder eine Änderung der Anleitung anzuregen.
