### ISSUE TITLE
Bad Gateway 502 Ubuntu 20.4

### ISSUE THREAD

**Issue by webber33** [JsBergbau/BaikalAnleitung#3]
Hallo,
habe einen LXC auf Proxmox mit Ubuntu 20.4.
Composer hat 36 Pakete installiert. Keine Fehlermeldungen.
Mit nano die baikal-nginx.site erzeugt.

Im Brower erscheint die Fehlermeldung 502. Die Adminseite ist nicht erreichbar.

Komme leider nicht weiter. Wo kann ich weiter suchen?

Danke für die tolle und ausführliche Anleitung.

**Comment by JsBergbau** [comment]
Hallo webber33,

vielen Dank für dein Lob.

Ich würde nochmal alle Pfade über prüfen. Wenn die stimmen die Berechtigungen/Eigentümer prüfen. Wenn die auch stimmen, läuft der nginx bei dir vermutlich nicht als Benutzer www-data.

**Comment by webber33** [comment]
So, jetzt läuft es. 
Danke für deine schnelle Antwort.
DIe Lösung war, den Pfad zu der PHP anzupassen. 
Habe PHP-version 7.4. 
Die config verweist allerdings auf 7.3.
Nochmal danke.

**Comment by JsBergbau** [comment]
Danke für die Rückmeldung. Die Anleitung ist nun angepasst um der neuen PHP Version auf Ubuntu Rechnung zu tragen https://github.com/JsBergbau/BaikalAnleitung/blob/master/README.md#webserver-konfiguration
