### ISSUE TITLE
Schritt  sudo systemctl restart nginx

### ISSUE THREAD

**Issue by Luthian0815** [JsBergbau/BaikalAnleitung#6]
Hallo,

der Schritt funktioniert nicht. ich bekomme die Meldung:
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.

 nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-01-08 13:46:17 CET; 1min 13s ago
     Docs: man:nginx(8)
  Process: 14213 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Jan 08 13:46:17 raspberrypi systemd[1]: Starting A high performance web server and a reverse proxy server...
Jan 08 13:46:17 raspberrypi nginx[14213]: nginx: [emerg] "listen" directive is not allowed here in /etc/nginx/sites-enabled/baikal-nginx.site:1
Jan 08 13:46:17 raspberrypi nginx[14213]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jan 08 13:46:17 raspberrypi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Jan 08 13:46:17 raspberrypi systemd[1]: nginx.service: Failed with result 'exit-code'.
Jan 08 13:46:17 raspberrypi systemd[1]: Failed to start A high performance web server and a reverse proxy server

Hat jemand eine Idee?

Danke, Luthian

**Comment by JsBergbau** [comment]
Hallo Luthian,

poste mal bitte deine Konfiguration hier.

> Jan 08 13:46:17 raspberrypi nginx[14213]: nginx: [emerg] "listen" directive is not allowed here in /etc/nginx/sites-enabled/baikal-nginx.site:1

Deutet schon auf einen Fehler in ihr hin.

**Comment by Luthian0815** [comment]
Peinlich, das war es...2x nachgeschaut und es übersehen...sorry dafür!

**Comment by JsBergbau** [comment]
Kein Problem, Fehler passieren.
