### ISSUE TITLE
Ergänzungswunsch - wie lighttpd für Baikal konfigurieren

### ISSUE THREAD

**Issue by hefrimu** [JsBergbau/BaikalAnleitung#7]
Hallo, vielen Dank für die ausführliche Anleitung. Ich habe einen Raspi auf dem bereits lighttpd läuft. Wäre es möglich alternativ zu beschreiben, wie dies für Baikal zu konfigurieren wäre?

**Comment by JsBergbau** [comment]
Hallo hefrimu,

vielen Dank für dein Interesse an der Baikal-Anleitung.

Sicherlich ist es möglich, die Anleitung für lighttpd anzupassen. Allerdings ist das für mich mit einigem Aufwand verbunden: Schauen wie lighthttpd konfiguriert wird bzw. dessen Syntax. Wenn dieser zusätzliche Weg dann aufgenommen ist, gilt es den natürlich genauso aktuell zu halten. Zwei verschiedene Varianten führen also auch in der Zukunft zu höherem Wartungsaufwand. 

Zum Ressourcenverbrauch: Ich kann das gar nicht so genau messen, da auf meinem Raspberry einige andere Dienste laufen und daher die physische RAM-Auslastung im "Leerlauf" ständig schwankt. Laut htop kommt die größte Speicherbelegung durch php bzw. php-fpm. Die CPU-Auslastung ist im Leerlauf 0 %. Ich habe auch noch ein paar weitere nginx Konfigurationen laufen, daher ist der genaue Speicherverbrauch schwer zu beziffern, dürfte aber im Bereich von wenigen MB liegen. Der zusätzliche Ressourcenverbrauch eines nginx gegenüber einem vorhandenen lighthttp ist daher aus meiner Sicht vernachlässigbar.

Aus diesem Grund habe ich mich entschieden offiziell nur nginx zu unterstützen und die freiwerdende Zeit lieber dafür zu verwenden Hilfestellung bei der vorhandenen Anleitung zu geben bzw. sie weiterzuentwickeln um den Funktionsumfang weiter zu erhöhen, wie z.B. neulich das Versenden von Einladungsmails.
