### ISSUE TITLE
Nginx failed to restart

### ISSUE THREAD

**Issue by foxleronic** [JsBergbau/BaikalAnleitung#8]
Moin,

nach dem Befehl
sudo ln -s /home/pi/DiensteUndProgramme/Baikal/baikal-nginx.site /etc/nginx/sites-enabled/baikal-nginx.site

bekomme ich bei restart des servers die Fehlermeldung

Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.

BG

**Comment by JsBergbau** [comment]
Hallo foxleronic,

bitte teile uns hier den Inhalt von baikal-nginx.site mit

**Comment by foxleronic** [comment]
Habe die aus dem Tutorial genommen

server {

    listen 9999 default_server;

    #listen [::]:80 default_server;
    # SSL configuration
    #
    # listen 443 ssl default_server;
    # listen [::]:443 ssl default_server;
    #
    # Note: You should disable gzip for SSL traffic.
    # See: https://bugs.debian.org/773332
    #
    # Read up on ssl_ciphers to ensure a secure configuration.
    # See: https://bugs.debian.org/765782
    #
    # Self signed certs generated by the ssl-cert package
    # Don't use them in a production server!
    #
    # include snippets/snakeoil.conf;
    #root /var/www/html;

    root /home/pi/DiensteUndProgramme/Baikal/html;

    # Add index.php to the list if you are using PHP

    index index.php index.html index.htm index.nginx-debian.html;
    server_name _;

    # location / {
    #     First attempt to serve request as file, then
    #     as directory, then fall back to displaying a 404. try_files $uri $uri/ =404;
    # }

    rewrite ^/.well-known/caldav /dav.php redirect;
    rewrite ^/.well-known/carddav /dav.php redirect;
    charset utf-8;

    location ~ /(\.ht|Core|Specific|config) {
        deny all;
        return 404;
    } #In der aktuellen Variante nicht benötigt, da "html" das Root Verzeichnis ist, schadet aber auch nicht.
	 #Sollte man Baikal jedoch direkt im Webserver als Unterverzeichnis installieren, absolut notwendig. Bitte daran denken!

    location ~ ^(.+.php)(.*)$ {
        try_files $fastcgi_script_name =404;
        include /etc/nginx/fastcgi_params;
        fastcgi_split_path_info ^(.+.php)(.*)$;
        fastcgi_pass unix:/run/php/php7.3-fpm.sock; #Hier auf eure installierte PHP-Version achten. 
	#fastcgi_pass unix:/run/php/php7.4-fpm.sock; #Ubuntu hat z.B. schon php 7.4
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #

    location ~ /.ht {
        deny all;
    }

}

**Comment by JsBergbau** [comment]
Zeilenendung passt? Also Linux Format? Kann z.B. mit Notepad++ geprüft werden.
Ansonsten bitte mal Ausgabe von  `cat /var/log/nginx/error.log` hier posten.

**Comment by foxleronic** [comment]
Ausagabe error.log

2021/02/15 15:11:28 [emerg] 13005#13005: open() "/etc/nginx/sites-enabled/baikal-nginx.site" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62
2021/02/15 15:12:14 [emerg] 13016#13016: open() "/etc/nginx/sites-enabled/baikal-nginx.site" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62
2021/02/15 15:14:11 [emerg] 529#529: open() "/etc/nginx/sites-enabled/baikal-nginx.site" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62
2021/02/15 15:20:16 [emerg] 1613#1613: open() "/etc/nginx/sites-enabled/baikal-nginx.site" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62
2021/02/15 15:23:40 [error] 1702#1702: *1 "/home/pi/DiensteUndProgramme/Baikal/html/index.php" is not found (2: No such file or directory), client: 192.168.8.101, server: _, request: "GET / HTTP/1.1", host: "192.168.8.197:9999"
2021/02/15 15:23:40 [error] 1702#1702: *1 open() "/home/pi/DiensteUndProgramme/Baikal/html/favicon.ico" failed (2: No such file or directory), client: 192.168.8.101, server: _, request: "GET /favicon.ico HTTP/1.1", host: "192.168.8.197:9999", referrer: "http://192.168.8.197:9999/"
2021/02/15 15:25:25 [error] 1702#1702: *3 "/home/pi/DiensteUndProgramme/Baikal/html/index.php" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:9999"
2021/02/15 15:25:25 [error] 1702#1702: *3 open() "/home/pi/DiensteUndProgramme/Baikal/html/favicon.ico" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localhost:9999", referrer: "http://localhost:9999/"
2021/02/15 15:30:58 [emerg] 2184#2184: open() "/etc/nginx/sites-enabled/baikal-nginx.site" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62

**Comment by JsBergbau** [comment]
Auf welchem Linux System richtest du es es ein?

Mach mal bitte `ls -l /home/pi/DiensteUndProgramme/Baikal/baikal-nginx.site` und teile die Ausgabe mit.

**Comment by foxleronic** [comment]
OK, habe den Fehler gefunden und behoben.

habe beim erstellen des Verzeichnisses DiensteUndProgramme das "U" kleine geschrieben.

Wer lesen und schreiben kann ist klar im Vorteil :)

Vielen Dank trotzdem für den schnellen Support.
