### ISSUE TITLE
Falscher Link zur Raspberry-Pi-Downloadseite

### ISSUE THREAD

**Issue by qwerty287** [JsBergbau/BaikalAnleitung#9]
Der Link zum Download von Raspbian bzw. Raspberry Pi OS ist falsch bzw. veraltet. 
Alter Link (so wie verlinkt): https://www.raspberrypi.org/downloads/raspbian/
Neuer Link: https://www.raspberrypi.org/software/operating-systems/#raspberry-pi-os-32-bit

**Comment by JsBergbau** [comment]
Hallo qwerty287,
vielen Dank. Link wurde aktualisiert.

**Comment by qwerty287** [comment]
Es wäre noch gut, "Raspbian" in "Raspberry Pi OS" umzubennen, was ja der neue Name davon ist. Könnte sonst ein bisschen verwirrend sein.

**Comment by JsBergbau** [comment]
Danke, habe es ausgebessert, auch wenn mir Raspian deutlich besser gefällt, denn Rasperry PI OS wirkt als wäre es das einzige Betriebssystem für den Raspberry PI. Leider scheint das gerade ein Modebegriff geworden zu sein. So gibt es ein iOS, ein Fritz!OS und was weiß ich noch alles....
